FROM ghcr.io/buka-lnc/nodejs-slim:18 as builder

ARG HOST='0.0.0.0'
ARG PORT=80
ARG STORAGE='./storage'
ARG REGISTRY='http://127.0.0.1:8080/api/registry'

ARG MYSQL__DB_NAME='opendoc'
ARG MYSQL__HOST
ARG MYSQL__PORT
ARG MYSQL__USER
ARG MYSQL__PASSWORD
ARG MYSQL__TIMEZONE='+08:00'

ARG PINO__PRETTY
ARG PINO__LEVEL='info'


COPY . /repo
WORKDIR /repo


RUN pnpm install --filter "backend..." --frozen-lockfile && turbo build --filter "@opendoc/backend..."

CMD ["bash", "-c", "cd /repo/app/backend && pnpm run start:prod"]
